import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  ModalCloseButton,
  Tag,
  VStack,
  HStack,
  Divider,
} from "@chakra-ui/react";
import { Button, Text } from "../../../../components";

const Field = ({ label, value }) => (
  <HStack justify="space-between" w="100%" align="flex-start">
    <Text fontSize="sm" color="gray.500" minW="140px">
      {label}
    </Text>
    <Text fontSize="sm" fontWeight="500" textAlign="right">
      {value ?? "—"}
    </Text>
  </HStack>
);

const engagementColorMap = { Active: "green", Irregular: "yellow", Inactive: "red" };

const ReportDetailModal = ({ isOpen, onClose, report }) => {
  if (!report) return null;

  return (
    <Modal isOpen={isOpen} onClose={onClose} size="lg">
      <ModalOverlay />
      <ModalContent>
        <ModalHeader>Report Details — {report.reportId}</ModalHeader>
        <ModalCloseButton />
        <ModalBody>
          <VStack spacing={3} align="stretch">
            <Field label="Student ID" value={report.studentId} />
            <Field label="Student Name" value={report.studentName} />
            <Field label="Email" value={report.studentEmail} />
            <Field label="Program" value={report.program} />
            <Field label="Course" value={report.course} />
            <Field label="Instructor" value={report.instructor} />
            <Divider />
            <Field label="Participation Score" value={`${report.participationScore}%`} />
            <Field label="Activity Type" value={report.activityType} />
            <Field label="Frequency of Access" value={report.frequencyOfAccess} />
            <Field label="Last Active Date" value={report.lastActiveDate} />
            <Field label="Days Inactive" value={report.daysSinceActive} />
            <HStack justify="space-between" w="100%">
              <Text fontSize="sm" color="gray.500">Engagement Status</Text>
              <Tag
                size="sm"
                borderRadius="full"
                colorScheme={engagementColorMap[report.engagementStatus] ?? "gray"}
              >
                {report.engagementStatus ?? "—"}
              </Tag>
            </HStack>
            <HStack justify="space-between" w="100%">
              <Text fontSize="sm" color="gray.500">Alert Triggered</Text>
              <Tag
                size="sm"
                borderRadius="full"
                colorScheme={report.alertTriggered ? "red" : "gray"}
              >
                {report.alertTriggered ? "Yes" : "No"}
              </Tag>
            </HStack>
            <Divider />
            <Field label="Generated By" value={report.generatedBy} />
            <Field label="Remarks" value={report.remarks} />
          </VStack>
        </ModalBody>
        <ModalFooter>
          <Button onClick={onClose}>Close</Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
};

export default ReportDetailModal;
