import { useEffect, useState } from "react";
import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  ModalCloseButton,
  Tag,
  VStack,
  HStack,
  Divider,
  Spinner,
  SimpleGrid,
  Box,
} from "@chakra-ui/react";
import { Button, Text } from "../../../../components";
import { pm2GetStudentParticipation } from "../../../../services";

const engagementColor = { Active: "green", Irregular: "yellow", Inactive: "red" };

const fmtDate = (d) =>
  d ? new Date(d).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }) : "—";

const Field = ({ label, value }) => (
  <HStack justify="space-between" w="100%" align="flex-start">
    <Text fontSize="sm" color="gray.500" minW="160px">{label}</Text>
    <Text fontSize="sm" fontWeight="500" textAlign="right">{value ?? "—"}</Text>
  </HStack>
);

const ActivityBadge = ({ types }) => {
  if (!types) return <Text fontSize="sm">—</Text>;
  const list = Array.isArray(types) ? types : [types];
  return (
    <HStack flexWrap="wrap" justify="flex-end">
      {list.map((t) => (
        <Tag key={t} size="sm" colorScheme="purple" borderRadius="full">{t}</Tag>
      ))}
    </HStack>
  );
};

// TC08 mode: student profile fields from /student-report
const TC08Detail = ({ report }) => (
  <VStack spacing={3} align="stretch">
    <Field label="Report ID" value={report.report_id} />
    <Field label="Student ID" value={report.student_id} />
    <Field label="Student Name" value={report.student_name} />
    <Field label="Email" value={report.email} />
    <Field label="Phone" value={report.phone} />
    <Field label="Address" value={report.address} />
    <Field label="Department" value={report.department} />
    <Divider />
    <Field label="Enrollment Status" value={report.enrollment_status} />
    <HStack justify="space-between" w="100%">
      <Text fontSize="sm" color="gray.500">Engagement Status</Text>
      <Tag size="sm" borderRadius="full" colorScheme={engagementColor[report.engagement_status] ?? "gray"}>
        {report.engagement_status ?? "—"}
      </Tag>
    </HStack>
    <HStack justify="space-between" w="100%">
      <Text fontSize="sm" color="gray.500">Participation Score</Text>
      <Text fontSize="sm" fontWeight="700"
        color={report.participation_score >= 70 ? "#1A8F3A" : report.participation_score >= 40 ? "#B7791F" : "#C53030"}>
        {report.participation_score}%
      </Text>
    </HStack>
    <Field label="Last Active Date" value={fmtDate(report.last_active_date)} />
    <Field label="Days Since Active" value={report.days_since_active} />
    <HStack justify="space-between" w="100%">
      <Text fontSize="sm" color="gray.500">Alert Triggered</Text>
      <Tag size="sm" borderRadius="full" colorScheme={report.alert_triggered ? "red" : "gray"}>
        {report.alert_triggered ? "Yes" : "No"}
      </Tag>
    </HStack>
    <Divider />
    <Field label="Generated By" value={report.generated_by} />
    <Field label="Generated At" value={fmtDate(report.generated_at)} />
    <Field label="Remarks" value={report.remarks} />
  </VStack>
);

// TC04 mode: full participation data from /report/{studentId}
const TC04Detail = ({ data }) => {
  const activityTypes = Array.isArray(data.activity_type) ? data.activity_type : null;
  return (
    <VStack spacing={3} align="stretch">
      <Field label="Student ID" value={data.student_id ?? data.studentId} />
      <Field label="Student Name" value={data.student_name} />
      <Field label="Email" value={data.student_email} />
      <Divider />
      <HStack justify="space-between" w="100%">
        <Text fontSize="sm" color="gray.500">Participation Score</Text>
        <Text fontSize="sm" fontWeight="700"
          color={data.participation_score >= 70 ? "#1A8F3A" : data.participation_score >= 40 ? "#B7791F" : "#C53030"}>
          {data.participation_score}%
        </Text>
      </HStack>
      <HStack justify="space-between" w="100%" align="flex-start">
        <Text fontSize="sm" color="gray.500" minW="160px">Activity Types</Text>
        <ActivityBadge types={activityTypes ?? data.activity_type} />
      </HStack>
      <Divider />
      <SimpleGrid columns={2} spacing={3}>
        <Box p={3} borderRadius="md" bg="gray.50" textAlign="center">
          <Text fontSize="xs" color="gray.500">Logins</Text>
          <Text fontSize="xl" fontWeight="700" color="#660066">{data.login_count ?? 0}</Text>
        </Box>
        <Box p={3} borderRadius="md" bg="gray.50" textAlign="center">
          <Text fontSize="xs" color="gray.500">Quizzes</Text>
          <Text fontSize="xl" fontWeight="700" color="#2C5282">{data.quiz_count ?? 0}</Text>
        </Box>
        <Box p={3} borderRadius="md" bg="gray.50" textAlign="center">
          <Text fontSize="xs" color="gray.500">Forum Posts</Text>
          <Text fontSize="xl" fontWeight="700" color="#1A8F3A">{data.forum_count ?? 0}</Text>
        </Box>
        <Box p={3} borderRadius="md" bg="gray.50" textAlign="center">
          <Text fontSize="xs" color="gray.500">Assignments</Text>
          <Text fontSize="xl" fontWeight="700" color="#B7791F">{data.assignment_count ?? 0}</Text>
        </Box>
      </SimpleGrid>
      <Divider />
      <Field label="Frequency of Access" value={data.frequency_of_access} />
      <Field label="Last Active Date" value={fmtDate(data.last_active_date)} />
      <Field label="Days Since Active" value={data.days_since_active} />
      <HStack justify="space-between" w="100%">
        <Text fontSize="sm" color="gray.500">Engagement Status</Text>
        <Tag size="sm" borderRadius="full" colorScheme={engagementColor[data.engagement_status] ?? "gray"}>
          {data.engagement_status ?? "—"}
        </Tag>
      </HStack>
      <HStack justify="space-between" w="100%">
        <Text fontSize="sm" color="gray.500">Alert Triggered</Text>
        <Tag size="sm" borderRadius="full" colorScheme={data.alert_triggered ? "red" : "gray"}>
          {data.alert_triggered ? "Yes" : "No"}
        </Tag>
      </HStack>
      <Divider />
      <Field label="Remarks" value={data.remarks} />
    </VStack>
  );
};

// mode: "tc08" | "tc04"
const ReportDetailModal = ({ isOpen, onClose, report, mode = "tc08" }) => {
  const [detail, setDetail] = useState(null);
  const [loading, setLoading] = useState(false);

  // For TC04 mode, fetch full single-student detail from /report/{studentId}
  useEffect(() => {
    if (!isOpen || mode !== "tc04" || !report?.student_id) {
      setDetail(null);
      return;
    }
    setLoading(true);
    pm2GetStudentParticipation(report.student_id)
      .then((res) => setDetail(res?.record ?? null))
      .catch(() => setDetail(report))
      .finally(() => setLoading(false));
  }, [isOpen, mode, report]);

  if (!report) return null;

  const title = mode === "tc08"
    ? `Student Report — ${report.report_id ?? report.reportId ?? ""}`
    : `Participation Detail — ${report.student_name ?? report.studentName ?? ""}`;

  return (
    <Modal isOpen={isOpen} onClose={onClose} size="lg" scrollBehavior="inside">
      <ModalOverlay />
      <ModalContent>
        <ModalHeader fontSize="md">{title}</ModalHeader>
        <ModalCloseButton />
        <ModalBody>
          {mode === "tc04" && loading ? (
            <Box display="flex" justifyContent="center" py={10}>
              <Spinner color="#660066" />
            </Box>
          ) : mode === "tc04" ? (
            <TC04Detail data={detail ?? report} />
          ) : (
            <TC08Detail report={report} />
          )}
        </ModalBody>
        <ModalFooter>
          <Button onClick={onClose}>Close</Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
};

export default ReportDetailModal;
