export * from "./courses/CoursesPage";
export * from "./courses/CourseListingPage/CourseListingPage";
export * from "./courses/CreateCoursePage";
export * from "./courses/CreateLessonPage";
export * from "./courses/ViewCourseInfoPage/layout/ViewCourseInfoPage";
export * from "./courses/ViewLessonInfoPage";
export * from "./DashboardPage";
export * from "./NotFoundPage";
export * from "./users/CreateUserPage/CreateUserPage";
export * from "./users/UserListingPage/UserListingPage";
export * from "./users/UserInfoPage/layout/UserInfoPage";
export * from "./users/UserInfoPage/pages/ProfilePage";
export * from "./users/UserInfoPage/pages/ExaminationRecordsPage";
export * from "./courses/AssessmentPage/layout/AssessmentPage";
export * from "./departments/DepartmentListingPage";
export * from "./departments/CreateDepartmentPage";
export * from "./departments/ViewDepartmentDetails";
export * from "./departments/AddExistingUsersPage";
export * from "./departments/BulkActionPage";
export * from "./RoleListingPage";
export * from "./settings/SettingsPage";
export * from "./settings/GradeCriteriaPage";
export * from "./settings/SecurityPage";
export * from "./events/EventsPage";
export * from "./events/CreateEventPage";
export * from "./lib/LibraryListingPage";
export * from "./lib/CreateLibraryFilePage";
export * from "./lib/ViewFileDetailsPage";
export * from "./standaloneExams/StandaloneExaminationListingPage";
export * from "./standaloneExams/StandaloneExaminationAllParticipantsPage";
export * from "./standaloneExams/ExaminationPage";
export * from "./standaloneExams/ExaminationDetailPage";
export * from "./standaloneExams/SingleExaminationPage";
export * from "./standaloneExams/GradeQuestionPage";
export * from "./audit/ViewAudit";
export * from "./documents/DocumentsPageRoute";
export * from "./report/ReportListingPage";
export * from "./report/ComplianceSecurityReportPage";
export * from "./report/CustomAdHocReportPage";
export * from "./report/ElectronicRegistersReportPage";
export * from "./report/TrackingReportingPage";
export * from "./report/MISReportsPage";
export * from "./report/AutomatedApprovalWorkflowPage";
export * from "./workflow/AutomatedApprovalWorkflow";
export * from "./workflow/ReviewSubmissionPage";
export * from "./examinationMarking/ExaminationMarkingPage";
export * from "./examinationMarking/CreateMarkingJobPage";
export * from "./examinationMarking/MarkingJobDetailsPage";
export * from "./examinationMarking/MarkPaperPage";
export * from "./examTemplates/ExamTemplatesPage";
export * from "./examTemplates/CreateExamTemplatePage";
export * from "./examTemplates/ExamTemplateDetailsPage";
export * from "./examTemplates/CreateQuestionBankPage";
export * from "./feedbackMarkup/FeedbackMarkupPage";
export * from "./feedbackMarkup/SubmissionReviewPage";
export * from "./gradeBook/GradeBookListingPage";
export * from "./gradeBook/CreateGradeBookPage";
export * from "./gradeBook/GradeBookDetailsPage";
export * from "./bulkCourse/BulkCourseListingPage";
export * from "./bulkCourse/CreateBulkCourseBatchPage";
export * from "./bulkCourse/BatchDetailsPage";
export * from "./userDocuments/UserDocumentsPage";
export * from "./userDocuments/UserDocumentDetailsPage";
export * from "./reportExport/ReportExportPage";
export * from "./questionImport/QuestionImportPage";
export * from "./questionImport/UploadDetailsPage";
export * from "./questionBankTemplate/QuestionBankTemplatesPage";
export * from "./questionBankTemplate/QuestionBankTemplateDetailsPage";
export * from "./courseContent/CourseContentEditorPage";
export * from "./courses/CreateModulePage";
export * from "./dataOperations/DataOperationsPage";
export { ModuleAssessmentsPageRoute } from "./courses/ViewCourseInfoPage/pages/ModuleAssessmentsPage";
export { CreateModuleAssessmentPageRoute } from "./courses/ViewCourseInfoPage/pages/CreateModuleAssessmentPage";
export { ModuleExaminationsPageRoute } from "./courses/ViewCourseInfoPage/pages/ModuleExaminationsPage";
export { CreateModuleExaminationPageRoute } from "./courses/ViewCourseInfoPage/pages/CreateModuleExaminationPage";
export { ViewModuleExaminationPageRoute } from "./courses/ViewCourseInfoPage/pages/ViewModuleExaminationPage";
export { ModuleProjectsPageRoute } from "./courses/ViewCourseInfoPage/pages/ModuleProjectsPage";
export { CreateModuleProjectPageRoute } from "./courses/ViewCourseInfoPage/pages/CreateModuleProjectPage";
export { ViewModuleProjectPageRoute } from "./courses/ViewCourseInfoPage/pages/ViewModuleProjectPage";
