export * from "./courses/CoursesPage";
export * from "./courses/CourseListingPage/CourseListingPage";
export * from "./courses/CreateCoursePage";
export * from "./courses/CreateLessonPage";
export * from "./courses/ViewCourseInfoPage/layout/ViewCourseInfoPage";
export * from "./courses/ViewLessonInfoPage";
export * from "./DashboardPage";
export * from "./NotFoundPage";
export * from "./users/CreateUserPage/CreateUserPage";
export * from "./users/UserListingPage/UserListingPage";
export * from "./users/UserInfoPage/layout/UserInfoPage";
export * from "./users/UserInfoPage/pages/ProfilePage";
export * from "./users/UserInfoPage/pages/ExaminationRecordsPage";
export * from "./courses/AssessmentPage/layout/AssessmentPage";
export * from "./departments/DepartmentListingPage";
export * from "./departments/CreateDepartmentPage";
export * from "./departments/ViewDepartmentDetails";
export * from "./departments/AddExistingUsersPage";
export * from "./departments/BulkActionPage";
export * from "./RoleListingPage";
export * from "./settings/SettingsPage";
export * from "./settings/GradeCriteriaPage";
export * from "./settings/SecurityPage";
export * from "./events/EventsPage";
export * from "./events/CreateEventPage";
export * from "./lib/LibraryListingPage";
export * from "./lib/CreateLibraryFilePage";
export * from "./lib/ViewFileDetailsPage";
export * from "./standaloneExams/StandaloneExaminationListingPage";
export * from "./standaloneExams/StandaloneExaminationAllParticipantsPage";
export * from "./standaloneExams/ExaminationPage";
export * from "./standaloneExams/ExaminationDetailPage";
export * from "./standaloneExams/SingleExaminationPage";
export * from "./standaloneExams/GradeQuestionPage";
export * from "./audit/ViewAudit";
export * from "./documents/DocumentsPageRoute";
export * from "./report/ReportListingPage";
export * from "./report/ComplianceSecurityReportPage";
export * from "./report/CustomAdHocReportPage";
export * from "./report/ReportBuilderPage";
export * from "./report/ElectronicRegistersReportPage";
export * from "./report/TrackingReportingPage";
export * from "./report/MISReportsPage";
export * from "./report/AutomatedApprovalWorkflowPage";
export * from "./workflow/AutomatedApprovalWorkflow";
export * from "./workflow/ReviewSubmissionPage";
export * from "./workflow/SubmitWorkflowPage";
export * from "./workflow/WorkflowTrackingPage";
export * from "./examinationMarking/ExaminationMarkingPage";
export * from "./examinationMarking/CreateMarkingJobPage";
export * from "./examinationMarking/MarkingJobDetailsPage";
export * from "./examinationMarking/MarkPaperPage";
export * from "./examTemplates/ExamTemplatesPage";
export * from "./examTemplates/CreateExamTemplatePage";
export * from "./examTemplates/ExamTemplateDetailsPage";
export * from "./examTemplates/CreateQuestionBankPage";
export * from "./feedbackMarkup/FeedbackMarkupPage";
export * from "./feedbackMarkup/SubmissionReviewPage";
export * from "./gradeBook/GradeBookListingPage";
export * from "./gradeBook/CreateGradeBookPage";
export * from "./gradeBook/GradeBookDetailsPage";
export * from "./userDocuments/UserDocumentsPage";
export * from "./userDocuments/UserDocumentDetailsPage";
export * from "./certificates/CertificateUploadPage/CertificateUploadPage";
export * from "./certificates/CertificateManagementPage/CertificateManagementPage";
export * from "./reportExport/ReportExportPage";
export * from "./questionImport/QuestionImportPage";
export * from "./questionImport/UploadDetailsPage";
export * from "./questionBankTemplate/QuestionBankTemplatesPage";
export * from "./questionBankTemplate/QuestionBankTemplateDetailsPage";
export * from "./courseContent/CourseContentEditorPage";
export * from "./courses/CreateModulePage";
export * from "./dataOperations/DataOperationsPage";
export * from "./courseRoster/CourseRosterPage/CourseRosterPage";
export * from "./courseRosterExport/CourseRosterExportPage";
export { ModuleAssessmentsPageRoute } from "./courses/ViewCourseInfoPage/pages/ModuleAssessmentsPage";
export { CreateModuleAssessmentPageRoute } from "./courses/ViewCourseInfoPage/pages/CreateModuleAssessmentPage";
export { ModuleExaminationsPageRoute } from "./courses/ViewCourseInfoPage/pages/ModuleExaminationsPage";
export { CreateModuleExaminationPageRoute } from "./courses/ViewCourseInfoPage/pages/CreateModuleExaminationPage";
export { ViewModuleExaminationPageRoute } from "./courses/ViewCourseInfoPage/pages/ViewModuleExaminationPage";
export { ViewModulePageRoute } from "./courses/ViewCourseInfoPage/pages/ViewModulePage";
export { ModuleProjectsPageRoute } from "./courses/ViewCourseInfoPage/pages/ModuleProjectsPage";
export { CreateModuleProjectPageRoute } from "./courses/ViewCourseInfoPage/pages/CreateModuleProjectPage";
export { ViewModuleProjectPageRoute } from "./courses/ViewCourseInfoPage/pages/ViewModuleProjectPage";
export { EditModuleProjectPageRoute } from "./courses/ViewCourseInfoPage/pages/EditModuleProjectPage";
export { ProjectSubmissionsPageRoute } from "./courses/ViewCourseInfoPage/pages/ProjectSubmissionsPage";
export { ProjectSubmissionReviewPageRoute } from "./courses/ViewCourseInfoPage/pages/ProjectSubmissionReviewPage";
export { ModuleProgressPageRoute } from "./courses/ViewCourseInfoPage/pages/ModuleProgressPage";
export { BulkCourseV2ListingPageRoute } from "./bulkCourse/v2/BulkCourseV2ListingPage";
export { CreateBulkCourseV2BatchPageRoute } from "./bulkCourse/v2/CreateBulkCourseV2BatchPage";
export { BulkCourseV2BatchDetailsPageRoute } from "./bulkCourse/v2/BulkCourseV2BatchDetailsPage";
export { TemplatesListingPageRoute } from "./bulkCourse/v2/TemplatesListingPage";
export { TemplateFormPageRoute } from "./bulkCourse/v2/TemplateFormPage";
export { ManualMarkingExamsPageRoute } from "./manualMarking/ManualMarkingExamsPage";
export { ManualMarkingStudentsPageRoute } from "./manualMarking/ManualMarkingStudentsPage";
export { StudentMarkingPageRoute } from "./manualMarking/StudentMarkingPage";
export { GradeBookV2ListingPageRoute } from "./gradeBookV2/GradeBookV2ListingPage";
export { SetupGradeBookV2PageRoute } from "./gradeBookV2/SetupGradeBookV2Page";
export { GradeBookV2DetailsPageRoute } from "./gradeBookV2/GradeBookV2DetailsPage";
export { ViewStandaloneExamPageRoute } from "./standaloneExams/ViewStandaloneExamPage";
export { StandaloneStudentGradingPageRoute } from "./standaloneExams/StandaloneStudentGradingPage";
export { QuestionBankPageRoute } from "./multimediaQuestions/QuestionBankPage";
export { QuestionEditorPageRoute } from "./multimediaQuestions/QuestionEditorPage";
export { QuestionPreviewPageRoute } from "./multimediaQuestions/QuestionPreviewPage";
export { MediaManagerPageRoute } from "./multimediaQuestions/MediaManagerPage";
export { MultimediaStatsPageRoute } from "./multimediaQuestions/MultimediaStatsPage";
export { ExamPaperConfigPageRoute } from "./examPaperConfig/ExamPaperConfigPage";
export { ExamConfigKPIPageRoute } from "./examPaperConfig/ExamConfigKPIPage";
export { BatchImportPageRoute } from "./questionBatchImport/BatchImportPage";
export { BatchHistoryPageRoute } from "./questionBatchImport/BatchHistoryPage";
export { ImportResultPageRoute } from "./questionBatchImport/ImportResultPage";
export { ImportReportPageRoute } from "./questionBatchImport/ImportReportPage";
export { BatchUploadPageRoute } from "./examQuestionImport/BatchUploadPage";
export { ReviewImportPageRoute } from "./examQuestionImport/ReviewImportPage";
export { PerformanceFiltersPageRoute } from "./report/performanceFilters/PerformanceFiltersPage";
export { VisualAnalyticsDashboardPageRoute } from "./report/visualAnalytics/VisualAnalyticsDashboardPage";
export { ProctoringAuditReportPageRoute } from "./report/proctoring/ProctoringAuditReportPage";
export { ExamSessionAuditPageRoute } from "./report/proctoring/ExamSessionAuditPage";
export { ProctoringKpiSummaryPageRoute } from "./report/proctoring/ProctoringKpiSummaryPage";
export { AdminExamResultAnalysisPageRoute } from "./examResultAnalysis/AdminExamResultAnalysisPage";
export { EnrollmentStatusReportPageRoute } from "./report/enrollmentStatusReport/EnrollmentStatusReportPage";
export { AuditTrailReportPageRoute } from "./report/auditTrail/AuditTrailReportPage";
export { ScheduledReportingPageRoute } from "./report/scheduledReporting/ScheduledReportingPage";
export { CourseMaterialUploadPageRoute } from "./courseMaterialUpload/CourseMaterialUploadPage/CourseMaterialUploadPage";
