import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  ModalCloseButton,
  Badge,
  Text,
  HStack,
  VStack,
  Divider,
  Button,
  SimpleGrid,
  Box,
  Tooltip,
} from "@chakra-ui/react";
import { FiInfo } from "react-icons/fi";
import dayjs from "dayjs";

const humanizeKey = (key) =>
  key
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/^./, (s) => s.toUpperCase())
    .trim();

// per GC LMS Enhancement Scoping Document — same field name can mean different
// things in different categories (e.g. departmentEnrollmentRate), so scope by category
const VARIABLE_DESCRIPTIONS = {
  academic: {
    courseEnrollmentCount: "Total enrolled courses.",
    courseCompletionRate: "Completion percentage.",
    averageGrade: "Mean performance score.",
    academicStanding: "Excellent/Good/etc.",
    assessmentCompletionRate: "Completed tests/quizzes.",
    activeCourses: "Ongoing courses.",
    certificationEarned: "Certificates issued.",
  },
  administrative: {
    totalRegisteredUsers: "Learners + instructors.",
    approvedUsers: "Active users.",
    instructorCount: "Active instructors.",
    departmentEnrollmentRate: "Enrollment per department.",
    courseAvailabilityStatus: "Published/unpublished.",
    userAccountStatus: "Approved/deactivated.",
    systemUsageRate: "Login frequency.",
  },
  compliance: {
    overallComplianceScore: "Institutional compliance.",
    departmentComplianceRate: "Compliance by department.",
    performanceComparisons: "Compare departments.",
    examinationSubmissionStatus: "Submission tracking.",
    complianceCourseStatus: "Mandatory course completion.",
    completionDate: "Date completed.",
  },
};

const formatValue = (val) => {
  if (val === null || val === undefined || val === "") return "—";
  if (typeof val === "boolean") return val ? "Yes" : "No";
  if (Array.isArray(val)) return val.length ? val.join(", ") : "—";
  if (typeof val === "object") return Object.keys(val).length ? JSON.stringify(val) : "—";
  return String(val);
};

const Field = ({ label, value }) => (
  <HStack justify="space-between" w="100%" align="flex-start">
    <Text fontSize="13px" color="#667085" minW="150px">{label}</Text>
    <Text fontSize="13px" fontWeight="500" color="#101928" textAlign="right">{value ?? "—"}</Text>
  </HStack>
);

const getStatusColor = (status) => {
  switch (status?.toLowerCase()) {
    case "generated": return { bg: "#ECFDF3", color: "#027A48" };
    case "archived":  return { bg: "#FEF3F2", color: "#B42318" };
    case "draft":     return { bg: "#FFFAEB", color: "#B54708" };
    default:          return { bg: "#F2F4F7", color: "#344054" };
  }
};

const MISReportDetailModal = ({ isOpen, onClose, report }) => {
  if (!report) return null;

  const filterEntries = Object.entries(report.filtersApplied ?? {}).filter(([, v]) => v !== null && v !== undefined && v !== "");
  const summaryEntries = Object.entries(report.summary ?? {});
  const categoryDescriptions = VARIABLE_DESCRIPTIONS[report.reportCategory?.toLowerCase()] ?? {};

  return (
    <Modal isOpen={isOpen} onClose={onClose} size="lg" scrollBehavior="inside" isCentered>
      <ModalOverlay bg="blackAlpha.300" backdropFilter="blur(2px)" />
      <ModalContent borderRadius="xl">
        <ModalHeader fontSize="lg" fontWeight="700" color="#101928">
          {report.reportName}
          <Text fontSize="13px" fontWeight="400" color="#667085" mt={1}>{report.reportId}</Text>
        </ModalHeader>
        <ModalCloseButton mt={3} mr={2} />
        <ModalBody>
          <VStack spacing={5} align="stretch">
            <HStack spacing={2} flexWrap="wrap">
              <Badge bg="#F4F0FF" color="#6B21A8" borderRadius="full" px={3} py={1} fontSize="11px" textTransform="capitalize">
                {report.reportCategory}
              </Badge>
              <Badge bg="#EFF8FF" color="#175CD3" borderRadius="full" px={3} py={1} fontSize="11px" textTransform="uppercase">
                {report.reportFormat}
              </Badge>
              <Badge bg="#F2F4F7" color="#344054" borderRadius="full" px={3} py={1} fontSize="11px" textTransform="capitalize">
                {report.frequency?.replace(/_/g, " ")}
              </Badge>
              <Badge
                bg={getStatusColor(report.status).bg} color={getStatusColor(report.status).color}
                borderRadius="full" px={3} py={1} fontSize="11px" textTransform="capitalize"
              >
                {report.status}
              </Badge>
            </HStack>

            <VStack spacing={2} align="stretch">
              <Field label="Generated By" value={report.generatedBy} />
              <Field
                label="Generated Date"
                value={report.generatedDate ? dayjs(report.generatedDate).format("DD MMM YYYY, hh:mm A") : "—"}
              />
              <Field label="Record Count" value={report.recordCount} />
              <Field label="Generation Time" value={report.generationTimeMs != null ? `${report.generationTimeMs} ms` : "—"} />
              <Field label="Scheduled" value={formatValue(report.isScheduled)} />
              <Field label="Access Level" value={formatValue(report.accessLevel)} />
              <Field label="Data Sources" value={formatValue(report.dataSources)} />
            </VStack>

            {filterEntries.length > 0 && (
              <>
                <Divider />
                <Box>
                  <Text fontSize="13px" fontWeight="600" color="#667085" mb={2}>Filters Applied</Text>
                  <VStack spacing={2} align="stretch">
                    {filterEntries.map(([key, value]) => (
                      <Field key={key} label={humanizeKey(key)} value={formatValue(value)} />
                    ))}
                  </VStack>
                </Box>
              </>
            )}

            {summaryEntries.length > 0 && (
              <>
                <Divider />
                <Box>
                  <Text fontSize="13px" fontWeight="600" color="#667085" mb={2}>Report Summary</Text>
                  <SimpleGrid columns={2} spacing={3}>
                    {summaryEntries.map(([key, value]) => {
                      const description = categoryDescriptions[key];
                      return (
                        <Box key={key} p={3} borderRadius="md" bg="gray.50">
                          <HStack spacing={1}>
                            <Text fontSize="11px" color="#667085">{humanizeKey(key)}</Text>
                            {description && (
                              <Tooltip label={description} placement="top" hasArrow>
                                <Box as="span" display="inline-flex" color="#98A2B3">
                                  <FiInfo size={11} />
                                </Box>
                              </Tooltip>
                            )}
                          </HStack>
                          <Text fontSize="15px" fontWeight="700" color="#660066">{formatValue(value)}</Text>
                        </Box>
                      );
                    })}
                  </SimpleGrid>
                </Box>
              </>
            )}

            <Divider />
            <Field label="Remarks" value={report.remarks} />
          </VStack>
        </ModalBody>
        <ModalFooter gap={3}>
          {report.downloadUrl && (
            <Button
              as="a" href={report.downloadUrl} target="_blank" rel="noopener noreferrer"
              variant="outline" borderColor="#660066" color="#660066"
              fontSize="14px" fontWeight="600" borderRadius="md"
            >
              Download
            </Button>
          )}
          <Button
            bg="#660066" color="white" _hover={{ bg: "#550055" }}
            fontSize="14px" fontWeight="600" borderRadius="md" onClick={onClose}
          >
            Close
          </Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
};

export default MISReportDetailModal;
